version: "3.4"
services:
  procesing:
    build: 
      context: ./procesing
    depends_on:
  #    - kafka
      - db-usuarios
    healthcheck: 
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    ports:
      - "5000:80"
    environment:
      KAFKA_BROKER: kafka:9092
      DATABASE_URL: postgresql://postgres-usuarios:postgres-usuarios@db-usuarios:5432/postgres-usuarios
    volumes:
      - ./procesing:/usr/local/app
    networks:
      - back-process
      - back-tier-usuarios
  #    - kong-net

  #SERVICIO para crud de cursos 
  #en python
  #puerto 5001
  cursos:
    build: 
      context: ./cursos
    depends_on:
#      - kafka
      - db-cursos
    healthcheck: 
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    ports:
      - "5001:81"
    environment:
      KAFKA_BROKER: kafka:9092
      DATABASE_URL: postgresql://postgres-cursos:postgres-cursos@db-cursos:5432/postgres-cursos
    volumes:
      - ./cursos:/usr/local/app
    networks:
      - back-tier-cursos 
 #     - kong-net
    

  #SERVICIO para crud de usuarios
  #en python
  #puerto 5002
  usuarios:
    build: 
      context: ./usuarios
    depends_on:
#      - kafka
      - db-usuarios
    healthcheck: 
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    ports:
      - "5002:82"
    environment:
      KAFKA_BROKER: kafka:9092
      DATABASE_URL: postgresql://postgres-usuarios:postgres-usuarios@db-usuarios:5432/postgres-usuarios
    networks:
      - back-tier-usuarios
 #     - kong-net 
    volumes:
      - ./usuarios:/usr/local/app

  #BD de Usuarios en PostgreSQL
  db-usuarios:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: "postgres-usuarios"
      POSTGRES_NAME: "postgres-usuarios"
      POSTGRES_USER: "postgres-usuarios"
      POSTGRES_PASSWORD: "postgres-usuarios"
    volumes:
      - "db-data-usuarios:/var/lib/postgresql/data"
      - "./healthchecks:/healthchecks"
    ports:
      - "5432:5432"
    healthcheck:
      test: /healthchecks/postgres.sh
      interval: "5s"
    networks:
      - back-tier-usuarios

  #BD de Cursos en PostgreSQL
  db-cursos:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: "postgres-cursos"
      POSTGRES_NAME: "postgres-cursos"
      POSTGRES_USER: "postgres-cursos"
      POSTGRES_PASSWORD: "postgres-cursos"
    volumes:
      - "db-data-cursos:/var/lib/postgresql/data"
      - "./healthchecks:/healthchecks"
    ports:
      - "5433:5432"
    healthcheck:
      test: /healthchecks/postgres.sh
      interval: "5s"
    networks:
      - back-tier-cursos

volumes:
  exclude:
  db-data-cursos:
  db-data-usuarios:
#  persist_volume:
#  postgres_data:
#  mongo_data:

networks:
#  frontend:
  back-tier-usuarios:
  back-tier-cursos:
  back-process:
#  kong-net:


